### ISSUE TITLE
missing architecture x86_64 of MediaEditor

### ISSUE THREAD

**Issue by googoodalls** [LanSoSdk/LanSongEditor_IOS#1]
cannot running on simulator.

**Comment by ChaosTong** [comment]
simulator just can't run , because the simulator's GPU suck.this sdk need to use GPU ,wrote in README in chinese
quote "注意:因为视频编辑用到GPU, 真机和模拟器的GPU差异太大, 当前我们的SDK 暂时只能在真机上运行, 请您知悉."
